<?php

/**
 * @file
 * This module provides a node type called 'Simple Content Type'
 */
// make sure you have this or the options function won't fire
require_once('simple_content_type.functions.inc');
/**
 * Implement hook_form() with the standard default form.
 */
function simple_content_type_form($node, $form_state) {
  return node_content_form($node, $form_state);
}
/**
 * Implements hook_form_alter().
 */
function simple_content_type_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id != 'simple_content_type_node_form')  {
    // this is not the form we are looking for
    return;
  }
  //modify the default value for the simple text field
  if (!isset($form['simple_content_type_textfield']['und']['0']['value']['#default_value']))  {
    $form['simple_content_type_textfield']['und']['0']['value']['#default_value'] = variable_get('simple_content_type_default_text', '');
  }
}
/**
 * Implements hook_menu().
 */
function simple_content_type_menu()  {
  
  // create the Andy Pangus admin category
  $items['admin/config/andy_pangus_admin'] = array(
    'title' => 'Andy Pangus Administration',
    'description' => 'Administration pages and tasks for Andy Pangus.',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer nodes'),
  );
  
  // add the configs page to the admin section
  $items['admin/config/andy_pangus_admin/simple_content_type_settings'] = array(
    'title' => 'Simple Content Type Settings',
    'description' => 'Configuration settings for the Simple Content Type module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simple_content_type_configs_form'),
    'file' => 'simple_content_type.admin.inc',
    'access arguments' => array('administer nodes'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}
/**
 * Implements hook_node_info().
 */
function simple_content_type_node_info() {
  
  $items['simple_content_type'] = array(
    'name' => t('Simple Content Type'),
    'type' => 'simple_content_type',
    'base' => 'node_content',
    'description' => t('A simple demonstration content type with a title and body.'),
    'has_title' => '1',
    'title_label' => t('Simple Title'),
    'body_label' => t('Simple Description'),
    'help' => t('Please fill in all fields.'),
  );
  
  return $items;
}